/**
 * Per-service OG image map.
 *
 * Each entry maps a service slug to its 1200×630 social preview card.
 * Cards are generated by:
 *   bash scripts/generate-service-og-cards.sh
 *
 * These paths are relative to the public/ directory and are used as
 * absolute URLs when combined with SITE.siteUrl.
 *
 * Used by:
 *  - Turkish unprefixed service pages (app/<slug>/page.tsx)
 *  - Localised catch-all (app/[lang]/[...slug]/page.tsx).
 *
 * The map is derived from the service hero registry, so a newly registered
 * service is expected to receive a matching card from the generator.
 */
import {
  getRegisteredServiceHeroSlugs,
} from '@/lib/service-og-image';
import { SITE } from '@/lib/site-config';

export const SERVICE_OG_IMAGES: Record<string, string> = Object.fromEntries(
  getRegisteredServiceHeroSlugs().map((slug) => [slug, `/images/og/og-${slug}.jpg`]),
);

/**
 * Returns a branded card for every registered service. A CMS-created slug may
 * not have a generated card yet; metadata must remain safe in that case, so it
 * falls back to the global site preview instead of throwing during rendering.
 */
export function getServiceOgImageUrl(slug: string, siteUrl: string): string {
  const path = SERVICE_OG_IMAGES[slug];
  return new URL(path ?? SITE.ogImage.url, siteUrl).toString();
}
