/**
 * Per-service OG image map.
 *
 * Each entry maps a service slug to its 1200×630 social preview card.
 * Cards are generated by:
 *   bash scripts/generate-service-og-cards.sh
 *
 * These paths are relative to the public/ directory and are used as
 * absolute URLs when combined with SITE.siteUrl.
 *
 * Used by:
 *  - Turkish unprefixed service pages (app/<slug>/page.tsx)
 *  - Localised catch-all (app/[lang]/[...slug]/page.tsx).
 *
 * The map is derived from the service hero registry, so a newly registered
 * service is expected to receive a matching card from the generator.
 */
import {
  getRegisteredServiceHeroSlugs,
  getServiceHeroImage,
} from '@/lib/service-og-image';

export const SERVICE_OG_IMAGES: Record<string, string> = Object.fromEntries(
  getRegisteredServiceHeroSlugs().map((slug) => [slug, `/images/og/og-${slug}.jpg`]),
);

/**
 * Returns a branded card for every registered service. The hero fallback only
 * applies to an unregistered slug, so a bad CMS value can never collapse
 * service shares onto the global site preview.
 */
export function getServiceOgImageUrl(slug: string, siteUrl: string): string {
  const path = SERVICE_OG_IMAGES[slug];
  return path ? `${siteUrl}${path}` : getServiceHeroImage(slug);
}
