'use client';
import { useEffect, useState } from 'react';
type Driver = { id: string; name: string; phone: string | null; isActive: boolean };
export default function DriversClient() {
 const [items, setItems] = useState<Driver[] | null>(null); const [error, setError] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState({ name: '', phone: '', notes: '', isActive: true }); const [saving, setSaving] = useState(false);
 async function load() { setItems(null); setError(''); try { const r = await fetch('/admin/api/drivers'); if (!r.ok) throw new Error(); setItems((await r.json()).items); } catch { setError('Sürücüler yüklenemedi.'); } }
 useEffect(() => { load(); }, []);
 function start(d?: Driver) { setEditing(d?.id ?? 'new'); setForm({ name: d?.name ?? '', phone: d?.phone ?? '', notes: '', isActive: d?.isActive ?? true }); }
 async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); try { const r = await fetch(editing === 'new' ? '/admin/api/drivers' : `/admin/api/drivers/${editing}`, { method: editing === 'new' ? 'POST' : 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!r.ok) throw new Error((await r.json()).error); setEditing(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Sürücü kaydedilemedi.'); } finally { setSaving(false); } }
 async function toggle(d: Driver) { setError(''); const r = await fetch(`/admin/api/drivers/${d.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ isActive: !d.isActive }) }); if (!r.ok) setError('Aktiflik değiştirilemedi.'); else await load(); }
 if (error) return <div role="alert" style={{ padding: 20, color: '#BE123C' }}>{error} <button onClick={load} style={{ minHeight: 44 }}>Yeniden dene</button></div>;
 if (!items) return <div aria-busy="true" style={{ padding: 32 }}>Sürücüler yükleniyor…</div>;
  return <div><button onClick={() => start()} style={{ minHeight: 44, marginBottom: 12 }}>+ Yeni sürücü</button>{editing && <form onSubmit={save} aria-label="Sürücü formu" style={{ display: 'grid', gap: 10, padding: 16, background: '#FFF', border: '1px solid #E2E8F0', marginBottom: 12 }}><label>Ad soyad<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Telefon<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label>Notlar<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><label><input type="checkbox" checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })} /> Aktif</label><div><button disabled={saving} type="submit">{saving ? 'Kaydediliyor…' : 'Kaydet'}</button> <button type="button" onClick={() => setEditing(null)}>Vazgeç</button></div></form>}{!items.length ? <div style={{ padding: 32, background: '#FFF' }}>Henüz sürücü kaydı yok.</div> : <div style={{ display: 'grid', gap: 10 }}>{items.map(d => <div key={d.id} style={{ padding: 16, background: '#FFF', border: '1px solid #E2E8F0', display: 'flex', gap: 12, justifyContent: 'space-between', flexWrap: 'wrap' }}><span><strong>{d.name}</strong>{d.phone && ` · ${d.phone}`}<br /><small>{d.isActive ? 'Aktif' : 'Pasif'}</small></span><span><button onClick={() => start(d)} style={{ minHeight: 40 }}>Düzenle</button> <button onClick={() => toggle(d)} style={{ minHeight: 40 }}>{d.isActive ? 'Pasifleştir' : 'Aktifleştir'}</button></span></div>)}</div>}</div>;
}