'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { DashboardData, DashboardTransfer } from './page';
import { formatTransferCountdown } from '@/lib/operations';

function Card({ title, count, detail, href, tone = 'neutral' }: { title: string; count: number; detail: string; href: string; tone?: 'neutral' | 'warning' | 'positive' }) {
  const colors = tone === 'warning' ? ['#FFF7ED', '#C2410C'] : tone === 'positive' ? ['#F0FDF4', '#15803D'] : ['#EFF6FF', '#1D4ED8'];
  return <Link href={href} style={{ textDecoration: 'none' }}><article aria-label={title} style={{ minHeight: 130, padding: 18, border: '1px solid #D8E1E9', borderRadius: 12, background: '#FFF' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><strong style={{ color: '#334E68' }}>{title}</strong><b style={{ color: colors[1], background: colors[0], padding: '5px 9px', borderRadius: 8 }}>{count}</b></div><p style={{ color: '#718596', fontSize: 13 }}>{detail}</p></article></Link>;
}
function FlowRow({ item, onAssign }: { item: DashboardTransfer; onAssign: (id: string) => void }) {
  return <li style={{ display: 'grid', gridTemplateColumns: '110px 1fr 1fr 1fr auto', gap: 12, alignItems: 'center', padding: '14px 16px', borderBottom: '1px solid #EDF2F7' }}><time dateTime={item.plannedPickupAt}>{new Intl.DateTimeFormat('tr-TR', { timeZone: 'Europe/Istanbul', hour: '2-digit', minute: '2-digit' }).format(new Date(item.plannedPickupAt))}</time><span><b>{item.pickupLocationSummary} → {item.dropoffLocationSummary}</b><br /><small>{item.routeSummary}</small></span><span>{item.vehicleName ?? 'Araç atanmadı'}</span><span>{item.driverName ?? 'Sürücü atanmadı'}<br /><small>{item.customerSummary}</small></span>{!item.driverId && <button onClick={() => onAssign(item.id)} style={{ minHeight: 44, padding: '8px 12px' }}>Ata</button>}</li>;
}
export default function DashboardOperations({ initial }: { initial: DashboardData }) {
  const data = initial; const [now, setNow] = useState(Date.now()); const [retrying, setRetrying] = useState(false); const [assigning, setAssigning] = useState<string | null>(null); const [drivers, setDrivers] = useState<Array<{ id: string; name: string }>>([]); const [vehicles, setVehicles] = useState<Array<{ id: string; name: string }>>([]); const [driverId, setDriverId] = useState(''); const [vehicleId, setVehicleId] = useState('');
  useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []);
  async function retry() { setRetrying(true); window.location.reload(); }
  async function openAssign(id: string) { setAssigning(id); const [d, v] = await Promise.all([fetch('/admin/api/drivers').then(r => r.json()), fetch('/admin/api/vehicles?limit=100').then(r => r.json())]); setDrivers((d.items ?? []).filter((x: { isActive: boolean }) => x.isActive)); setVehicles((v.items ?? []).filter((x: { isActive: boolean }) => x.isActive)); }
  async function assign() { if (!assigning || !driverId) return; const r = await fetch(`/admin/api/transfers/${assigning}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ driverId, vehicleId: vehicleId || null }) }); if (r.ok) location.reload(); else alert('Atama yapılamadı.'); }
  return <div>
    {data.error && <div role="alert" style={{ padding: 14, marginBottom: 16, background: '#FFF1F2', color: '#BE123C' }}>{data.error} <button onClick={retry} disabled={retrying} style={{ minHeight: 44 }}>{retrying ? 'Yükleniyor…' : 'Yeniden dene'}</button></div>}
    <section aria-label="Operasyon özeti" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 16, marginBottom: 28 }}>
      <Card title="Bugünkü transferler" count={data.today.length} detail={formatTransferCountdown(data.nextPickupAt, new Date(now))} href="/admin/transferler?date=today" />
      <Card title="Atama bekleyen" count={data.unassignedCount} detail={data.unassignedCount ? 'Müdahale gerekiyor' : 'Tüm transferler atanmış'} tone={data.unassignedCount ? 'warning' : 'positive'} href="/admin/transferler?assigned=false" />
      <Card title="Yanıt bekleyen fiyat talepleri" count={data.quoteCount} detail="Gerçek QUOTE talepleri" href="/admin/talepler?intent=QUOTE&status=NEW" />
      <Card title="Yarınki transferler" count={data.tomorrowCount} detail="İstanbul saat dilimi" href="/admin/transferler?date=tomorrow" />
    </section>
     {assigning && <div role="dialog" aria-modal="true" aria-label="Transfer atama" style={{ position: 'fixed', inset: 0, background: '#0006', display: 'grid', placeItems: 'center', zIndex: 10 }}><form onSubmit={e => { e.preventDefault(); void assign(); }} style={{ background: '#FFF', padding: 24, borderRadius: 10, minWidth: 280 }}><h2>Atama yap</h2><label>Sürücü<select required autoFocus value={driverId} onChange={e => setDriverId(e.target.value)}><option value="">Sürücü seçin</option>{drivers.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Araç<select value={vehicleId} onChange={e => setVehicleId(e.target.value)}><option value="">Araç seçin</option>{vehicles.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div><button type="submit">Ata</button> <button type="button" onClick={() => setAssigning(null)}>İptal</button></div></form></div>}<section><h2 style={{ fontSize: 16, color: '#52697A' }}>Bugünün Transfer Akışı</h2>{data.today.length ? <ul style={{ listStyle: 'none', padding: 0, background: '#FFF', border: '1px solid #D8E1E9', borderRadius: 12, overflow: 'hidden' }}>{data.today.map(item => <FlowRow key={item.id} item={item} onAssign={openAssign} />)}</ul> : <div style={{ padding: 28, background: '#FFF', border: '1px solid #D8E1E9' }}>Bugün planlanmış transfer bulunmuyor.</div>}</section>
    <section><h2 style={{ fontSize: 16, color: '#52697A' }}>Bekleyen İşler</h2>{data.pending.length ? data.pending.map(p => <Link key={p.id} href={p.href} style={{ display: 'block', padding: 14 }}>{p.label}</Link>) : <div style={{ padding: 28, background: '#FFF', border: '1px solid #D8E1E9' }}>Bekleyen iş bulunmuyor.</div>}</section>
     <style>{`@media(max-width:768px){section[aria-label="Operasyon özeti"]{grid-template-columns:repeat(2,minmax(0,1fr))!important}li{grid-template-columns:90px 1fr!important}}@media(max-width:390px){section[aria-label="Operasyon özeti"]{grid-template-columns:1fr!important}li{grid-template-columns:1fr!important}}`}</style>
  </div>;
}